import type { Product, Category, Review, BlogPost, Faq } from './types';
import { categoryImages, productImages as productImagesMap, blogImages as blogImagesMap } from './placeholder-images';

const futureDate = (days: number) => new Date(new Date().getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const siteWideSale = {
  name: "Happy Christmas Sale",
  discountPercentage: 30,
  isActive: true,
};

export const categories: Category[] = [
  { id: '1', slug: 'sofas', name: 'Sofas', imageId: 'category-living-room', imageUrl: categoryImages['living-room'].imageUrl, imageHint: categoryImages['living-room'].imageHint },
  { id: '2', slug: 'beds', name: 'Beds', imageId: 'category-bedroom', imageUrl: categoryImages['bedroom'].imageUrl, imageHint: categoryImages['bedroom'].imageHint },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'urban-elegance-sofa',
    name: 'Urban Elegance Sectional Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1299.99,
    rating: 4.5,
    reviewCount: 120,
    imageIds: productImagesMap['urban-elegance-sofa'].map(i => i.id),
    description: 'A masterpiece of modern design, this sectional sofa offers unparalleled comfort and style. Its modular design allows for versatile arrangements to fit any living space.',
    details: ['Plush, high-density foam cushions', 'Durable linen-blend upholstery', 'Solid wood frame', 'Includes two matching throw pillows'],
    dimensions: { width: '280cm', height: '85cm', depth: '160cm' },
    style: 'Modern',
    material: 'Linen',
    stock: 15,
  },
  {
    id: '11',
    slug: 'ambassador-park-lane-bed',
    name: 'Ambassador Park Lane Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1450.00,
    rating: 5,
    reviewCount: 45,
    imageIds: productImagesMap['ambassador-bed'].map(i => i.id),
    description: 'Experience regal comfort with the Ambassador Park Lane bed. Its towering, deep-buttoned headboard makes a grand statement, while the plush velvet upholstery offers a soft and luxurious feel.',
    details: ['Statement 70-inch floor-standing headboard', 'Deep-buttoned chesterfield design', 'Luxurious crushed velvet finish', 'Solid and sturdy frame construction'],
    dimensions: { width: '165cm', height: '180cm', depth: '215cm' },
    style: 'Luxury',
    material: 'Velvet',
    stock: 12,
  },
  {
    id: '12',
    slug: 'astral-sleigh-bed',
    name: 'Astral Sleigh Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1350.00,
    rating: 4.8,
    reviewCount: 60,
    imageIds: productImagesMap['sleigh-bed'].map(i => i.id),
    description: 'The Astral Sleigh Bed features a classic, gracefully curved headboard and footboard, upholstered in a sumptuous grey fabric. Its timeless silhouette brings an air of romance and sophistication to any bedroom.',
    details: ['Classic sleigh bed design with rolled headboard and footboard', 'Upholstered in premium, soft-touch fabric', 'Deep button tufting for a luxurious look', 'Solid wood feet for stability'],
    dimensions: { width: '160cm', height: '135cm', depth: '225cm' },
    style: 'Classic',
    material: 'Fabric',
    stock: 8,
  },
  {
    id: '13',
    slug: 'divan-ottoman-bed',
    name: 'Divan Ottoman Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1150.00,
    rating: 4.9,
    reviewCount: 78,
    imageIds: productImagesMap['divan-ottoman-bed'].map(i => i.id),
    description: 'A perfect blend of style and practicality, the Divan Ottoman Bed offers a huge amount of under-bed storage space without compromising on comfort. The gas-lift mechanism makes accessing your stored items effortless.',
    details: ['Powerful gas-lift ottoman mechanism', 'Large, fully-boarded storage area', 'Upholstered in high-quality linen fabric', 'Comes with a matching 24-inch headboard'],
    dimensions: { width: '155cm', height: '105cm', depth: '205cm' },
    style: 'Modern',
    material: 'Linen',
    stock: 20,
  },
  {
    id: '14',
    slug: 'florida-mirror-bed',
    name: 'Florida Mirror Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1550.00,
    rating: 4.9,
    reviewCount: 55,
    imageIds: productImagesMap['mirror-bed'].map(i => i.id),
    description: 'Reflect your sophisticated taste with the Florida Mirror Bed. Featuring striking mirrored panels on the headboard and footboard, this bed adds a touch of glamour and light to any bedroom, creating a sense of space and luxury.',
    details: ['Elegant mirrored panels on headboard and footboard', 'Upholstered in plush, silver velvet', 'Modern, clean-lined silhouette', 'Sturdy frame with sprung slats for comfort'],
    dimensions: { width: '162cm', height: '140cm', depth: '212cm' },
    style: 'Glamour',
    material: 'Velvet',
    stock: 9,
  },
  {
    id: '15',
    slug: 'panel-ambassador-bed',
    name: 'Panel Ambassador Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1400.00,
    rating: 4.8,
    reviewCount: 40,
    imageIds: productImagesMap['panel-ambassador-bed'].map(i => i.id),
    description: 'The Panel Ambassador Bed offers a contemporary take on a classic design. Its clean, vertical panels on the headboard create a sense of height and modernity, while the soft upholstery provides a comfortable and inviting feel.',
    details: ['Tall, vertically-paneled headboard', 'Upholstered in a sophisticated chenille fabric', 'Solid platform base for excellent support', 'Clean lines for a modern aesthetic'],
    dimensions: { width: '160cm', height: '150cm', depth: '210cm' },
    style: 'Contemporary',
    material: 'Chenille',
    stock: 15,
  },
  {
    id: '16',
    slug: 'panel-bumper-bed',
    name: 'Panel Bumper Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1380.00,
    rating: 4.9,
    reviewCount: 35,
    imageIds: productImagesMap['panel-bumper-bed'].map(i => i.id),
    description: 'With its fully upholstered frame and padded "bumper" sides, this bed offers a soft and safe sleeping environment. The clean lines of the paneled headboard provide a modern touch to this exceptionally comfortable bed.',
    details: ['Fully padded and upholstered bumper frame', 'Modern paneled headboard design', 'Soft-touch woven fabric', 'Excellent for homes with young children'],
    dimensions: { width: '165cm', height: '130cm', depth: '215cm' },
    style: 'Modern',
    material: 'Fabric',
    stock: 11,
  },
  {
    id: '17',
    slug: 'panel-line-bed',
    name: 'Panel Line Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1390.00,
    rating: 4.8,
    reviewCount: 38,
    imageIds: productImagesMap['panel-line-bed'].map(i => i.id),
    description: 'This bed features clean, modern lines with its distinctive vertically-paneled headboard. Upholstered in a durable and stylish fabric, it offers a sophisticated centerpiece for any contemporary bedroom.',
    details: ['Striking vertical panel stitching on headboard', 'Upholstered in premium textured fabric', 'Low-profile footboard for a modern look', 'Solid wood slat system for durable support'],
    dimensions: { width: '160cm', height: '135cm', depth: '210cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 14,
  },
  {
    id: '18',
    slug: 'panel-wing-back-bed',
    name: 'Panel Wing Back Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1420.00,
    rating: 4.9,
    reviewCount: 42,
    imageIds: productImagesMap['panel-wing-back-bed'].map(i => i.id),
    description: 'A modern classic, the Panel Wing Back Bed features a grand, winged headboard with clean, vertical lines. It creates a cozy, enclosed feeling while making a bold style statement.',
    details: ['Grand wingback headboard design', 'Elegant vertical panel tufting', 'Upholstered in premium bouclé fabric', 'Provides a cozy, sheltered feel'],
    dimensions: { width: '168cm', height: '145cm', depth: '218cm' },
    style: 'Contemporary',
    material: 'Bouclé',
    stock: 10,
  },
  {
    id: '10',
    slug: 'minimalist-storage-bed',
    name: 'Minimalist Storage Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 1100.00,
    rating: 4.9,
    reviewCount: 95,
    imageIds: productImagesMap['minimalist-storage-bed'].map(i => i.id),
    description: 'Maximize your space with this clever minimalist bed, featuring four large under-bed storage drawers. Its clean lines and white finish suit any modern decor.',
    details: ['Four large soft-close storage drawers', 'Durable engineered wood with a matte white finish', 'No box spring needed', 'Perfect for compact living spaces'],
    dimensions: { width: '150cm', height: '100cm', depth: '200cm' },
    style: 'Minimalist',
    material: 'Wood',
    stock: 10,
  },
];

export const reviews: Review[] = [
  { id: '1', productId: '1', author: 'Jane D.', rating: 5, title: 'Absolutely stunning!', comment: 'The sofa is even more beautiful in person. It\'s comfortable, stylish, and was delivered right on time. Highly recommend!', date: '2023-08-15' },
  { id: '2', productId: '1', author: 'Mark S.', rating: 4, title: 'Great sofa, minor issue', comment: 'Love the look and feel. One of the legs was slightly scratched on arrival, but customer service was fantastic and sent a replacement immediately.', date: '2023-08-20' },
  { id: '3', productId: '2', author: 'Emily R.', rating: 5, title: 'Perfect dining table', comment: 'This table is the heart of our home now. The quality of the oak is outstanding. We\'ve had so many compliments!', date: '2023-07-05' },
  { id: '4', productId: '3', author: 'Sarah K.', rating: 5, title: 'Bedroom transformed!', comment: 'The Cloud Nine bed is a dream. It was easy to assemble and has completely transformed our bedroom into a luxury retreat.', date: '2023-09-01' },
  { id: '5', productId: '4', author: 'Tom B.', rating: 4.5, title: 'Stylish and comfortable', comment: 'This armchair is the perfect reading chair. It\'s firm but comfortable and looks incredibly stylish in my living room.', date: '2023-09-10' },
  { id: '6', productId: '1', author: 'Chris P.', rating: 4, title: 'Solid and stylish', comment: 'A really great sofa for the price. It is firm, which I like. The color is slightly different than online but it still works.', date: '2023-09-15' },
  { id: '7', productId: '1', author: 'Jessica L.', rating: 5, title: 'My dream sofa!', comment: 'I am so in love with this sofa. It is the perfect size for my apartment and so comfortable. Assembly was surprisingly easy.', date: '2023-10-02' },
  { id: '8', productId: '2', author: 'David H.', rating: 5, title: 'Outstanding Quality', comment: 'Solid wood, beautifully finished. You can tell this table is built to last. Worth every penny.', date: '2023-09-22' },
  { id: '9', productId: '2', author: 'Laura C.', rating: 4, title: 'Beautiful but heavy!', comment: 'It\'s a gorgeous table, but be prepared, it is extremely heavy! You will need two people to assemble it.', date: '2023-10-11' },
  { id: '10', productId: '3', author: 'Michael B.', rating: 5, title: 'Sleeps like a baby', comment: 'I was hesitant to buy a bed online but this was a great decision. The headboard is so soft and it feels very sturdy.', date: '2023-09-05' },
  { id: '11', productId: '4', author: 'Olivia W.', rating: 5, title: 'The perfect accent chair', comment: 'This chair completed my living room. The leather is high quality and the wood has a beautiful grain. It\'s a work of art.', date: '2023-10-18' },
  { id: '12', productId: '5', author: 'Ben A.', rating: 5, title: 'Makes me want to work', comment: 'This desk is incredible. The walnut is beautiful and it has so much space. My home office finally feels complete.', date: '2023-09-28' },
  { id: '13', productId: '5', author: 'Chloe G.', rating: 4, title: 'Great desk, drawers a bit small', comment: 'I love the look and feel of the desk. The surface is huge. I just wish the drawers were a little deeper, but it\'s a minor complaint.', date: '2023-10-08' },
  { id: '14', productId: '6', author: 'Liam T.', rating: 5, title: 'Perfect for my apartment', comment: 'Fits perfectly in my small living room and holds a surprising number of books. It was also very easy to put together by myself.', date: '2023-10-14' },
  { id: '15', productId: '6', author: 'Sophia N.', rating: 3, title: 'Looks good, but feels a bit wobbly', comment: 'The shelf looks great, but it doesn\'t feel as sturdy as I\'d hoped. Definitely need to use the wall anchors it came with.', date: '2023-10-20' },
  { id: '16', productId: '7', author: 'Daniel R.', rating: 5, title: 'Elegant and functional', comment: 'This lamp is a showstopper. It provides great light for reading on the sofa and the marble base is very heavy and stable.', date: '2023-09-30' },
  { id: '17', productId: '7', author: 'Grace P.', rating: 4, title: 'Love it, but tricky to position', comment: 'A beautiful lamp. The arc is quite large, so make sure you have enough space for it. It took a few tries to get it in the perfect spot.', date: '2023-10-05' },
  { id: '18', productId: '8', author: 'Ethan K.', rating: 5, title: 'So soft and beautiful', comment: 'The rug feels amazing underfoot. The pattern is subtle but adds so much character to the room. It unrolled flat almost immediately.', date: '2023-09-18' },
  { id: '19', productId: '8', author: 'Mia V.', rating: 5, title: 'Completes the room!', comment: 'This rug was the final piece my living room needed. The quality is excellent and the colors are true to the photos online.', date: '2023-10-25' },
  { id_ts: '20', productId: '4', author: 'Noah F.', rating: 5, title: 'My new favorite spot', comment: 'I find myself sitting in this chair all the time. It looks great and is surprisingly comfortable for long periods. A fantastic purchase.', date: '2023-10-28' }
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: '10-tips-for-choosing-the-perfect-sofa',
    title: '10 Tips for Choosing the Perfect Sofa',
    author: 'The Furnishr Team',
    date: 'October 26, 2023',
    imageId: 'blog-1',
    excerpt: 'Your sofa is the centerpiece of your living room. Here are 10 essential tips to help you choose a sofa that you\'ll love for years to come...',
    content: '<h2>Introduction</h2><p>Choosing a sofa is a big decision. It\'s often one of the largest and most-used pieces of furniture in a home. In this guide, we\'ll walk you through 10 key considerations...</p><h3>1. Measure Your Space</h3><p>Before you even start looking, measure the room, doorways, and stairwells to ensure your new sofa will fit. Don\'t forget to account for diagonal measurements of doorways! Use masking tape on the floor to outline the sofa\'s dimensions to get a real feel for how it will occupy the space.</p><h3>2. Consider Your Lifestyle</h3><p>Do you have children or pets? If so, opt for durable, stain-resistant fabrics like performance velvet or a tight-weave linen blend. If it\'s just for you, you might indulge in a more delicate material.</p><h3>3. Define Your Style</h3><p>Are you a mid-century modern enthusiast or do you prefer a classic, traditional look? Your sofa choice should complement your home\'s existing decor. Look at the legs, arm style, and overall silhouette.</p>',
    imageUrl: blogImagesMap['blog-1'].imageUrl,
    imageHint: blogImagesMap['blog-1'].imageHint
  },
  {
    id: '2',
    slug: 'how-to-style-a-small-living-space',
    title: 'How to Style a Small Living Space for Maximum Impact',
    author: 'The Furnishr Team',
    date: 'November 05, 2023',
    imageId: 'blog-2',
    excerpt: 'Living in a small space doesn\'t mean you have to compromise on style. With a few clever tricks, you can make your compact home feel spacious and chic...',
    content: '<h2>Embrace Multifunctionality</h2><p>In a small space, every piece of furniture should work hard. Think coffee tables with hidden storage, ottomans that double as seating, or sofas that convert into beds. This reduces clutter and maximizes utility.</p><h3>2. Go Vertical</h3><p>Utilize wall space with tall, narrow bookshelves and floating shelves to draw the eye upward and free up floor space. This creates an illusion of height and provides valuable storage and display areas without bulk.</p><h3>3. Use Light and Mirrors</h3><p>Mirrors are a small space\'s best friend. They reflect light and create a sense of depth, making the room feel larger. Position a large mirror opposite a window to maximize natural light. Choose a light color palette for walls and large furniture pieces to keep the space feeling airy and open.</p>',
    imageUrl: blogImagesMap['blog-2'].imageUrl,
    imageHint: blogImagesMap['blog-2'].imageHint
  },
  {
    id: '3',
    slug: 'biophilic-design-bringing-the-outdoors-in',
    title: 'Biophilic Design: Bringing the Outdoors In',
    author: 'The Furnishr Team',
    date: 'November 12, 2023',
    imageId: 'blog-3',
    excerpt: 'Discover how to incorporate natural elements into your home to create a calming, healthier, and more beautiful living environment. It\'s easier than you think...',
    content: '<h2>What is Biophilic Design?</h2><p>Biophilic design is an architectural and interior design approach that seeks to connect building occupants more closely to nature. Incorporating natural lighting, ventilation, plant life, and natural materials like wood and stone can reduce stress and improve well-being.</p><h3>1. Start with Plants</h3><p>The easiest way to begin is by adding houseplants. They purify the air and add a splash of color and life. Choose a variety of sizes and types, from large floor plants like a Fiddle Leaf Fig to small succulents on a windowsill.</p><h3>2. Natural Materials</h3><p>Incorporate materials that come from the earth. Think wooden furniture, stone countertops, linen curtains, and wool rugs. These textures add warmth and a sense of grounding to your space. Our Nordic Oak Dining Table is a perfect example!</p>',
    imageUrl: blogImagesMap['blog-3'].imageUrl,
    imageHint: blogImagesMap['blog-3'].imageHint
  }
];

export const faqs: Faq[] = [
    {
      id: '1',
      question: 'What payment methods do you accept?',
      answer: 'We accept all major credit cards (Visa, Mastercard, American Express), as well as PayPal, Klarna, Apple Pay, and Google Pay for a secure and seamless checkout experience.',
      category: 'Ordering',
    },
    {
      id: '2',
      question: 'How can I track my order?',
      answer: 'Once your order has shipped, you will receive an email with a tracking number and a link to the courier\'s website. You can use this to monitor your delivery status.',
      category: 'Shipping & Delivery',
    },
    {
      id: '3',
      question: 'What is your return policy?',
      answer: 'We offer a 30-day hassle-free return policy. If you are not completely satisfied with your purchase, you can return it within 30 days for a full refund or exchange. Please ensure the item is in its original condition and packaging.',
      category: 'Returns & Exchanges',
    },
    {
      id: '4',
      question: 'Do you offer free shipping?',
      answer: 'Yes, we offer free standard UK delivery on all orders over £250. For orders under £250, a standard delivery fee applies.',
      category: 'Shipping & Delivery',
    },
    {
      id: '5',
      question: 'Do your products come with a warranty?',
      answer: 'Absolutely. All our furniture comes with a 1-year manufacturer\'s warranty covering any defects in materials or craftsmanship. We stand by the quality of our products.',
      category: 'Product Information',
    },
    {
      id: '6',
      question: 'Can I cancel or change my order?',
      answer: 'You can cancel or modify your order within 24 hours of placing it. Please contact our customer service team as soon as possible. After 24 hours, the order may have already been processed for shipping.',
      category: 'Ordering',
    },
     {
      id: '7',
      question: 'How do I care for my new furniture?',
      answer: 'Each product comes with specific care instructions. Generally, we recommend dusting regularly, avoiding direct sunlight, and cleaning spills immediately with a dry cloth. For specific materials like leather or velvet, please refer to the care guide included with your item.',
      category: 'Product Information',
    },
];

export const featuredProducts: Product[] = [];

export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);
export const getBlogBySlug = (slug: string) => blogPosts.find(p => p.slug === slug);
