import type { Product, Category, Review, BlogPost } from './types';
import { categoryImages, productImages as productImagesMap, blogImages as blogImagesMap } from './placeholder-images';

export const categories: Category[] = [
  { id: '1', slug: 'living-room', name: 'Living Room', imageId: 'category-living-room', imageUrl: categoryImages['living-room'].imageUrl, imageHint: categoryImages['living-room'].imageHint },
  { id: '2', slug: 'bedroom', name: 'Bedroom', imageId: 'category-bedroom', imageUrl: categoryImages['bedroom'].imageUrl, imageHint: categoryImages['bedroom'].imageHint },
  { id: '3', slug: 'dining', name: 'Dining', imageId: 'category-dining', imageUrl: categoryImages['dining'].imageUrl, imageHint: categoryImages['dining'].imageHint },
  { id: '4', slug: 'office', name: 'Office', imageId: 'category-office', imageUrl: categoryImages['office'].imageUrl, imageHint: categoryImages['office'].imageHint },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'urban-elegance-sofa',
    name: 'Urban Elegance Sectional Sofa',
    category: 'Living Room',
    categorySlug: 'living-room',
    price: 1299.99,
    rating: 4.5,
    reviewCount: 120,
    imageIds: productImagesMap['urban-elegance-sofa'].map(i => i.id),
    description: 'A masterpiece of modern design, this sectional sofa offers unparalleled comfort and style. Its modular design allows for versatile arrangements to fit any living space.',
    details: ['Plush, high-density foam cushions', 'Durable linen-blend upholstery', 'Solid wood frame', 'Includes two matching throw pillows'],
    dimensions: { width: '280cm', height: '85cm', depth: '160cm' },
    style: 'Modern',
    material: 'Linen',
    stock: 15,
  },
  {
    id: '2',
    slug: 'nordic-oak-dining-table',
    name: 'Nordic Oak Dining Table',
    category: 'Dining',
    categorySlug: 'dining',
    price: 799.00,
    rating: 4.8,
    reviewCount: 85,
    imageIds: productImagesMap['nordic-oak-table'].map(i => i.id),
    description: 'Gather your loved ones around this beautiful Scandinavian-inspired dining table. Crafted from solid oak, it comfortably seats six and adds a touch of natural warmth to your dining room.',
    details: ['Seats 6-8 people', 'Made from 100% solid oak', 'Protective clear lacquer finish', 'Easy to assemble'],
    dimensions: { width: '180cm', height: '75cm', depth: '90cm' },
    style: 'Scandinavian',
    material: 'Oak',
    stock: 25,
  },
  {
    id: '3',
    slug: 'cloud-nine-platform-bed',
    name: 'Cloud Nine Platform Bed',
    category: 'Bedroom',
    categorySlug: 'bedroom',
    price: 950.50,
    rating: 4.9,
    reviewCount: 210,
    imageIds: productImagesMap['cloud-nine-bed'].map(i => i.id),
    description: 'Drift off to sleep on our Cloud Nine bed. With a luxurious upholstered headboard and a sturdy platform base, it\'s the perfect centerpiece for a serene and stylish bedroom.',
    details: ['Soft, velvety upholstery', 'No box spring required', 'Robust wooden slat system', 'Available in Queen and King sizes'],
    dimensions: { width: '160cm', height: '110cm', depth: '210cm' },
    style: 'Contemporary',
    material: 'Velvet',
    stock: 0,
  },
  {
    id: '4',
    slug: 'artisans-touch-armchair',
    name: 'Artisan\'s Touch Armchair',
    category: 'Living Room',
    categorySlug: 'living-room',
    price: 450.00,
    rating: 4.7,
    reviewCount: 95,
    imageIds: productImagesMap['artisans-touch-chair'].map(i => i.id),
    description: 'A statement piece that combines comfort and artistry. This armchair features a solid teak frame and genuine leather upholstery, aging beautifully over time.',
    details: ['Genuine top-grain leather', 'Hand-carved teak wood frame', 'Ergonomic design for maximum comfort', 'Compact footprint for any room'],
    dimensions: { width: '75cm', height: '80cm', depth: '85cm' },
    style: 'Mid-Century',
    material: 'Leather',
    stock: 8,
  },
  {
    id: '5',
    slug: 'executive-wooden-desk',
    name: 'The Executive Desk',
    category: 'Office',
    categorySlug: 'office',
    price: 620.00,
    rating: 4.6,
    reviewCount: 78,
    imageIds: productImagesMap['executive-desk'].map(i => i.id),
    description: 'Command your workspace with The Executive Desk. Made from rich walnut, it offers a spacious surface and two discreet drawers for storage, blending functionality with sophisticated design.',
    details: ['Solid walnut wood construction', 'Large work surface', 'Two soft-close drawers', 'Integrated cable management'],
    dimensions: { width: '140cm', height: '76cm', depth: '60cm' },
    style: 'Classic',
    material: 'Walnut',
    stock: 12,
  },
  {
    id: '6',
    slug: 'ladder-style-bookshelf',
    name: 'Ladder-Style Bookshelf',
    category: 'Office',
    categorySlug: 'office',
    price: 280.00,
    rating: 4.4,
    reviewCount: 150,
    imageIds: productImagesMap['ladder-bookshelf'].map(i => i.id),
    description: 'A stylish and space-saving solution for your books and decor. This industrial-style ladder bookshelf combines a metal frame with rustic wood shelves.',
    details: ['Five spacious tiers', 'Powder-coated steel frame', 'Reclaimed pine wood shelves', 'Wall-mounting hardware included'],
    dimensions: { width: '60cm', height: '180cm', depth: '50cm' },
    style: 'Industrial',
    material: 'Metal',
    stock: 30,
  },
  {
    id: '7',
    slug: 'arc-floor-lamp',
    name: 'Arc Floor Lamp',
    category: 'Living Room',
    categorySlug: 'living-room',
    price: 189.99,
    rating: 4.5,
    reviewCount: 65,
    imageIds: productImagesMap['arc-floor-lamp'].map(i => i.id),
    description: 'Illuminate your space with this elegant arc floor lamp. Its sweeping form and marble base make it a perfect addition over a sofa or reading corner.',
    details: ['Brushed brass finish', 'Solid marble base for stability', 'Adjustable shade', 'Foot switch for easy operation'],
    dimensions: { width: '120cm', height: '200cm', depth: '30cm' },
    style: 'Modern',
    material: 'Brass',
    stock: 4,
  },
  {
    id: '8',
    slug: 'geo-pattern-rug',
    name: 'Geo Pattern Rug',
    category: 'Living Room',
    categorySlug: 'living-room',
    price: 350.00,
    rating: 4.8,
    reviewCount: 92,
    imageIds: productImagesMap['geo-pattern-rug'].map(i => i.id),
    description: 'Define your space with this hand-tufted wool rug. Featuring a subtle geometric pattern, it adds texture and warmth to any room.',
    details: ['100% New Zealand wool', 'Hand-tufted by skilled artisans', 'Medium pile height (0.5 inch)', 'Available in multiple sizes'],
    dimensions: { width: '240cm', height: '1cm', depth: '170cm' },
    style: 'Bohemian',
    material: 'Wool',
    stock: 40,
  },
];

export const reviews: Review[] = [
  { id: '1', productId: '1', author: 'Jane D.', rating: 5, title: 'Absolutely stunning!', comment: 'The sofa is even more beautiful in person. It\'s comfortable, stylish, and was delivered right on time. Highly recommend!', date: '2023-08-15' },
  { id: '2', productId: '1', author: 'Mark S.', rating: 4, title: 'Great sofa, minor issue', comment: 'Love the look and feel. One of the legs was slightly scratched on arrival, but customer service was fantastic and sent a replacement immediately.', date: '2023-08-20' },
  { id: '3', productId: '2', author: 'Emily R.', rating: 5, title: 'Perfect dining table', comment: 'This table is the heart of our home now. The quality of the oak is outstanding. We\'ve had so many compliments!', date: '2023-07-05' },
  { id: '4', productId: '3', author: 'Sarah K.', rating: 5, title: 'Bedroom transformed!', comment: 'The Cloud Nine bed is a dream. It was easy to assemble and has completely transformed our bedroom into a luxury retreat.', date: '2023-09-01' },
  { id: '5', productId: '4', author: 'Tom B.', rating: 4.5, title: 'Stylish and comfortable', comment: 'This armchair is the perfect reading chair. It\'s firm but comfortable and looks incredibly stylish in my living room.', date: '2023-09-10' },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: '10-tips-for-choosing-the-perfect-sofa',
    title: '10 Tips for Choosing the Perfect Sofa',
    author: 'The Furnishr Team',
    date: 'October 26, 2023',
    imageId: 'blog-1',
    excerpt: 'Your sofa is the centerpiece of your living room. Here are 10 essential tips to help you choose a sofa that you\'ll love for years to come...',
    content: '<h2>Introduction</h2><p>Choosing a sofa is a big decision. It\'s often one of the largest and most-used pieces of furniture in a home. In this guide, we\'ll walk you through 10 key considerations...</p><h3>1. Measure Your Space</h3><p>Before you even start looking, measure the room, doorways, and stairwells to ensure your new sofa will fit. Don\'t forget to account for diagonal measurements of doorways! Use masking tape on the floor to outline the sofa\'s dimensions to get a real feel for how it will occupy the space.</p><h3>2. Consider Your Lifestyle</h3><p>Do you have children or pets? If so, opt for durable, stain-resistant fabrics like performance velvet or a tight-weave linen blend. If it\'s just for you, you might indulge in a more delicate material.</p><h3>3. Define Your Style</h3><p>Are you a mid-century modern enthusiast or do you prefer a classic, traditional look? Your sofa choice should complement your home\'s existing decor. Look at the legs, arm style, and overall silhouette.</p>',
    imageUrl: blogImagesMap['blog-1'].imageUrl,
    imageHint: blogImagesMap['blog-1'].imageHint
  },
  {
    id: '2',
    slug: 'how-to-style-a-small-living-space',
    title: 'How to Style a Small Living Space for Maximum Impact',
    author: 'The Furnishr Team',
    date: 'November 05, 2023',
    imageId: 'blog-2',
    excerpt: 'Living in a small space doesn\'t mean you have to compromise on style. With a few clever tricks, you can make your compact home feel spacious and chic...',
    content: '<h2>Embrace Multifunctionality</h2><p>In a small space, every piece of furniture should work hard. Think coffee tables with hidden storage, ottomans that double as seating, or sofas that convert into beds. This reduces clutter and maximizes utility.</p><h3>2. Go Vertical</h3><p>Utilize wall space with tall, narrow bookshelves and floating shelves to draw the eye upward and free up floor space. This creates an illusion of height and provides valuable storage and display areas without bulk.</p><h3>3. Use Light and Mirrors</h3><p>Mirrors are a small space\'s best friend. They reflect light and create a sense of depth, making the room feel larger. Position a large mirror opposite a window to maximize natural light. Choose a light color palette for walls and large furniture pieces to keep the space feeling airy and open.</p>',
    imageUrl: blogImagesMap['blog-2'].imageUrl,
    imageHint: blogImagesMap['blog-2'].imageHint
  }
];

export const featuredProducts = products.slice(0, 4);

export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);
export const getBlogBySlug = (slug: string) => blogPosts.find(p => p.slug === slug);
