
import type { Product, Category, Review, BlogPost, Faq } from './types';
import { categoryImages, productImages as productImagesMap, blogImages as blogImagesMap } from './placeholder-images';

const futureDate = (days: number) => new Date(new Date().getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const siteWideSale = {
  name: "Happy Christmas Sale",
  discountPercentage: 30,
  isActive: true,
};

export const categories: Category[] = [
  { id: '1', slug: 'sofas', name: 'Sofas', imageId: 'category-living-room', imageUrl: categoryImages['living-room'].imageUrl, imageHint: categoryImages['living-room'].imageHint },
  { id: '2', slug: 'beds', name: 'Beds', imageId: 'category-bedroom', imageUrl: categoryImages['bedroom'].imageUrl, imageHint: categoryImages['bedroom'].imageHint },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'aokland-sofa',
    name: 'Aokland Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 280.00,
    variants: [
        { size: '1 Seater', price: 250.00 },
        { size: '2 Seater', price: 280.00 },
        { size: '3 Seater', price: 320.00 },
        { size: '4 Seater', price: 380.00 },
    ],
    rating: 4.5,
    reviewCount: 120,
    imageIds: productImagesMap['aokland-sofa'].map(i => i.id),
    description: 'A masterpiece of modern design, this sectional sofa offers unparalleled comfort and style. Its modular design allows for versatile arrangements to fit any living space.',
    details: ['Plush, high-density foam cushions', 'Durable linen-blend upholstery', 'Solid wood frame', 'Includes two matching throw pillows'],
    dimensions: { width: '280cm', height: '85cm', depth: '160cm' },
    style: 'Modern',
    material: 'Linen',
    stock: 15,
  },
  {
    id: '19',
    slug: 'artic-sofa-bed',
    name: 'Artic Sofa Bed',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 590.00,
    rating: 4.7,
    reviewCount: 35,
    imageIds: productImagesMap['artic-sofa-bed'].map(i => i.id),
    description: 'The perfect blend of style and functionality. The Artic Sofa Bed transitions effortlessly from a chic sofa to a comfortable bed, making it ideal for small spaces or guest rooms.',
    details: ['Easy-to-use click-clack mechanism', 'Comfortable foam mattress', 'Durable and soft fabric upholstery', 'Solid wood legs'],
    dimensions: { width: '210cm', height: '88cm', depth: '90cm' },
    style: 'Scandinavian',
    material: 'Fabric',
    stock: 18,
  },
  {
    id: '20',
    slug: 'ashwin-sofa-bed',
    name: 'Ashwin Sofa Bed',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 290.00,
    variants: [
      { size: '1 Seater', price: 270.00 },
      { size: '2 Seater', price: 290.00 },
      { size: '3 Seater', price: 350.00 },
      { size: '5 Seater', price: 490.00 },
    ],
    rating: 4.6,
    reviewCount: 28,
    imageIds: productImagesMap['ashwin-sofa-bed'].map(i => i.id),
    description: 'The Ashwin Sofa Bed is a versatile and stylish addition to any home. With its plush cushions and easy-to-convert mechanism, it offers a comfortable seating solution by day and a cozy bed by night.',
    details: ['Smooth pull-out bed mechanism', 'High-density foam for comfort and support', 'Upholstered in a durable, textured fabric', 'Modern design with clean lines'],
    dimensions: { width: '220cm', height: '90cm', depth: '95cm' },
    style: 'Modern',
    material: 'Fabric',
    stock: 22,
  },
  {
    id: '21',
    slug: 'chesterfield-sofa',
    name: 'Chesterfield Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 440.00,
    variants: [
      { size: '1 Seater', price: 380.00 },
      { size: '2 Seater', price: 440.00 },
      { size: '3 Seater', price: 480.00 },
      { size: '5 Seater', price: 760.00 },
    ],
    rating: 4.9,
    reviewCount: 88,
    imageIds: productImagesMap['chesterfield-sofa'].map(i => i.id),
    description: 'An icon of timeless British design, the Chesterfield sofa features deep button tufting, rolled arms, and a low back. Upholstered in premium leather, this sofa is a statement piece that exudes luxury and sophistication.',
    details: ['Classic deep button tufting', 'Elegant scrolled arms', 'Upholstered in 100% genuine top-grain leather', 'Solid hardwood frame and bun feet'],
    dimensions: { width: '225cm', height: '76cm', depth: '95cm' },
    style: 'Classic',
    material: 'Leather',
    stock: 10,
  },
  {
    id: '22',
    slug: 'dino-sofa',
    name: 'Dino Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 320,
    variants: [
      { size: '1 Seater', price: 280 },
      { size: '2 Seater', price: 320 },
      { size: '3 Seater', price: 350 },
      { size: '5 Seater', price: 490 },
    ],
    rating: 4.7,
    reviewCount: 42,
    imageIds: productImagesMap['dino-sofa'].map(i => i.id),
    description: 'The Dino Sofa is the epitome of comfort. With its deep seats, plush cushions, and soft-to-the-touch fabric, it\'s the perfect sofa for family movie nights or relaxing with a good book.',
    details: ['Extra-deep seats for ultimate comfort', 'High-resilience foam cushions wrapped in fiber', 'Durable yet soft woven fabric', 'Modern, low-profile design'],
    dimensions: { width: '240cm', height: '85cm', depth: '105cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 15,
  },
  {
    id: '23',
    slug: 'dylan-sofa',
    name: 'Dylan Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 280.00,
    variants: [
      { size: '1 Seater', price: 250.00 },
      { size: '2 Seater', price: 280.00 },
      { size: '3 Seater', price: 320.00 },
      { size: '5 Seater', price: 380.00 },
    ],
    rating: 4.8,
    reviewCount: 52,
    imageIds: productImagesMap['dylan-sofa'].map(i => i.id),
    description: 'The Dylan Sofa combines sleek, modern lines with inviting comfort. Upholstered in a rich blue velvet, it features clean track arms and plush cushions, making it a sophisticated centerpiece for any living space.',
    details: ['Luxurious blue velvet upholstery', 'High-density foam cushions for superior comfort', 'Slim track arms for a modern look', 'Solid wood frame for durability'],
    dimensions: { width: '215cm', height: '84cm', depth: '92cm' },
    style: 'Modern',
    material: 'Velvet',
    stock: 14,
  },
  {
    id: '24',
    slug: 'electric-recliner-sofa',
    name: 'Electric Recliner Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 360,
    variants: [
      { size: '1 Seater', price: 299 },
      { size: '2 Seater', price: 360 },
      { size: '3 Seater', price: 399 },
      { size: '3+2 Seater', price: 670 },
      { size: '5 Seater Corner', price: 690 },
    ],
    rating: 4.9,
    reviewCount: 65,
    imageIds: productImagesMap['electric-recliner-sofa'].map(i => i.id),
    description: 'Experience ultimate relaxation with the Electric Recliner Sofa. At the touch of a button, recline into your perfect position of comfort. Upholstered in premium, durable leather with USB charging ports for convenience.',
    details: ['Smooth and quiet electric reclining mechanism', 'Integrated USB charging ports', 'Premium top-grain leather upholstery', 'Plush headrests and lumbar support'],
    dimensions: { width: '210cm', height: '102cm', depth: '98cm' },
    style: 'Contemporary',
    material: 'Leather',
    stock: 8,
  },
  {
    id: '25',
    slug: 'harrison-sofa',
    name: 'Harrison Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 290,
    variants: [
      { size: '1 Seater', price: 270 },
      { size: '2 Seater', price: 290 },
      { size: '3 Seater', price: 350 },
      { size: '3+2 Seater', price: 490 },
    ],
    rating: 4.8,
    reviewCount: 72,
    imageIds: productImagesMap['harrison-sofa'].map(i => i.id),
    description: 'The Harrison Sofa brings a touch of contemporary elegance to any living room. With its clean lines, comfortable cushions, and stylish metal legs, it is the perfect blend of form and function.',
    details: ['Upholstered in a durable and soft woven fabric', 'High-resilience foam cushions for lasting comfort', 'Sleek metal legs for a modern look', 'Sturdy solid wood frame'],
    dimensions: { width: '230cm', height: '86cm', depth: '94cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 16,
  },
  {
    id: '26',
    slug: 'ikea-berlin-sofa-bed',
    name: 'Ikea Berlin Sofa Bed',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 399.00,
    variants: [
      { size: '2 Seater', price: 399.00 },
      { size: '3 Seater', price: 949.99 },
    ],
    rating: 4.5,
    reviewCount: 30,
    imageIds: productImagesMap['ikea-berlin-sofa-bed'].map(i => i.id),
    description: 'The Ikea Berlin Sofa Bed is the epitome of Scandinavian functionality. Its minimalist design, clever hidden storage, and effortless transformation from sofa to bed make it a must-have for modern, compact living.',
    details: ['Simple and intuitive pull-out mechanism', 'Spacious under-seat storage compartment', 'Upholstered in a durable, easy-to-clean grey fabric', 'Classic Scandinavian design with light wood legs'],
    dimensions: { width: '225cm', height: '86cm', depth: '105cm' },
    style: 'Scandinavian',
    material: 'Fabric',
    stock: 25,
  },
  {
    id: '27',
    slug: 'lilly-sofa',
    name: 'Lilly Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1199.99,
    variants: [
      { size: '2 Seater', price: 1199.99 },
      { size: '3 Seater', price: 1399.99 },
    ],
    rating: 4.6,
    reviewCount: 38,
    imageIds: productImagesMap['lilly-sofa'].map(i => i.id),
    description: 'The Lilly Sofa offers a chic, feminine touch to any living space. With its gracefully curved arms and soft, textured upholstery, it provides both comfort and a sophisticated aesthetic. Perfect for creating a welcoming and stylish atmosphere.',
    details: ['Elegant curved armrests', 'Upholstered in a soft, durable bouclé fabric', 'High-density foam cushions for plush comfort', 'Tapered solid wood legs for a mid-century modern feel'],
    dimensions: { width: '200cm', height: '85cm', depth: '90cm' },
    style: 'Modern',
    material: 'Bouclé',
    stock: 18,
  },
  {
    id: '28',
    slug: 'mini-u-shape-sofa',
    name: 'Mini U-Shape Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1399.99,
    variants: [
      { size: '5 Seater', price: 1399.99 },
      { size: '6 Seater', price: 1599.99 },
    ],
    rating: 4.7,
    reviewCount: 45,
    imageIds: productImagesMap['mini-u-shape-sofa'].map(i => i.id),
    description: 'Maximise your seating in a compact space with the Mini U-Shape Sofa. This clever design offers the sociable layout of a U-shape sofa without overwhelming the room. Perfect for apartments or smaller living areas.',
    details: ['Space-efficient U-shape design', 'Plush, comfortable cushions', 'Upholstered in a durable, family-friendly fabric', 'Modular pieces for easy delivery and setup'],
    dimensions: { width: '280cm', height: '88cm', depth: '150cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 12,
  },
  {
    id: '29',
    slug: 'roma-leather-recliner-sofa',
    name: 'Roma Leather Recliner Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 2099.99,
    variants: [
      { size: '2 Seater', price: 2099.99 },
      { size: '3 Seater', price: 2399.99 },
    ],
    rating: 4.9,
    reviewCount: 75,
    imageIds: productImagesMap['roma-leather-recliner-sofa'].map(i => i.id),
    description: 'Indulge in luxurious comfort with the Roma Leather Recliner Sofa. Upholstered in premium Italian leather, this sofa features a smooth power reclining mechanism, allowing you to find your perfect position for relaxation at the touch of a button.',
    details: ['Upholstered in 100% top-grain Italian leather', 'Whisper-quiet power reclining mechanism', 'High-density foam core with a plush fiber wrap', 'Sturdy frame with a combination of solid wood and steel'],
    dimensions: { width: '215cm', height: '100cm', depth: '95cm' },
    style: 'Modern',
    material: 'Leather',
    stock: 7,
  },
  {
    id: '30',
    slug: 'shannon-sofa',
    name: 'Shannon Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1099.99,
    variants: [
      { size: '2 Seater', price: 1099.99 },
      { size: '3 Seater', price: 1299.99 },
    ],
    rating: 4.7,
    reviewCount: 68,
    imageIds: productImagesMap['shannon-sofa'].map(i => i.id),
    description: 'The Shannon Sofa is a stunning combination of textures and tones. With a mix of faux leather and soft fabric, along with its elegant curved arms, this sofa brings a touch of glamour to any living room.',
    details: ['Mix of faux leather and soft chenille fabric', 'Stylish curved armrests', 'Comfortable foam-filled seat cushions', 'Comes with matching scatter cushions'],
    dimensions: { width: '235cm', height: '90cm', depth: '90cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 20,
  },
   {
    id: '31',
    slug: 'sorrento-fabric-recliner',
    name: 'Sorrento Fabric Recliner',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1799.99,
    variants: [
      { size: '2 Seater', price: 1799.99 },
      { size: '3 Seater', price: 2099.99 },
    ],
    rating: 4.8,
    reviewCount: 58,
    imageIds: productImagesMap['sorrento-fabric-recliner'].map(i => i.id),
    description: 'Unwind in style with the Sorrento Fabric Recliner. Upholstered in a plush, durable fabric, this sofa offers deep cushioning and an effortless reclining motion for ultimate comfort. Perfect for movie nights or afternoon naps.',
    details: ['Smooth manual reclining mechanism', 'Upholstered in a soft and durable chenille fabric', 'Overstuffed cushions for a sink-in feel', 'Solid hardwood frame for long-lasting durability'],
    dimensions: { width: '205cm', height: '100cm', depth: '98cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 15,
  },
  {
    id: '32',
    slug: 'verona-u-shape-sofa',
    name: 'Verona U-Shape Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 2299.99,
    variants: [
        { size: '6 Seater', price: 2299.99 },
        { size: '7 Seater', price: 2599.99 },
    ],
    rating: 4.8,
    reviewCount: 55,
    imageIds: productImagesMap['verona-u-shape-sofa'].map(i => i.id),
    description: 'The Verona U-Shape Sofa is the ultimate centerpiece for large living spaces and entertaining guests. Its expansive design provides ample seating for the whole family, while its plush cushions and soft fabric ensure maximum comfort.',
    details: ['Generously sized U-shape design for maximum seating', 'Deep, comfortable cushions with foam and fiber filling', 'Upholstered in a premium, durable woven fabric', 'Modular design for flexible arrangement and easy transport'],
    dimensions: { width: '330cm', height: '90cm', depth: '200cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 9,
  },
  {
    id: '33',
    slug: 'verona-sofa',
    name: 'Verona Sofa',
    category: 'Sofas',
    categorySlug: 'sofas',
    price: 1199.99,
    variants: [
      { size: '2 Seater', price: 1199.99 },
      { size: '3 Seater', price: 1399.99 },
    ],
    rating: 4.7,
    reviewCount: 62,
    imageIds: productImagesMap['verona-sofa'].map(i => i.id),
    description: 'The Verona Sofa is a testament to modern elegance. It features clean lines, plush cushions, and a durable fabric upholstery that is both comfortable and stylish. Its timeless design makes it a perfect fit for any contemporary living space.',
    details: ['Clean, contemporary design', 'High-resilience foam cushions for comfort and durability', 'Upholstered in a premium, soft-touch woven fabric', 'Solid wood frame for lasting stability'],
    dimensions: { width: '220cm', height: '88cm', depth: '95cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 18,
  },
  {
    id: '11',
    slug: 'ambassador-park-lane-bed',
    name: 'Ambassador Park Lane Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 340.00,
    variants: [
      { size: 'Double', price: 340.00, mattressPrice: 440.00 },
      { size: 'King', price: 400.00, mattressPrice: 490.00 },
      { size: 'Super King', price: 450.00, mattressPrice: 550.00 },
    ],
    rating: 5,
    reviewCount: 45,
    imageIds: productImagesMap['ambassador-bed'].map(i => i.id),
    description: 'Experience regal comfort with the Ambassador Park Lane bed. Its towering, deep-buttoned headboard makes a grand statement, while the plush velvet upholstery offers a soft and luxurious feel.',
    details: ['Statement 70-inch floor-standing headboard', 'Deep-buttoned chesterfield design', 'Luxurious crushed velvet finish', 'Solid and sturdy frame construction'],
    dimensions: { width: '155cm', height: '180cm', depth: '218cm' },
    style: 'Luxury',
    material: 'Velvet',
    stock: 12,
  },
  {
    id: '12',
    slug: 'astral-sleigh-bed',
    name: 'Astral Sleigh Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 200.00,
    variants: [
      { size: 'Single', price: 200.00, mattressPrice: 430.00 },
      { size: 'Double', price: 230.00, mattressPrice: 490.00 },
      { size: 'King', price: 240.00, mattressPrice: 530.00 },
      { size: 'Super King', price: 260.00, mattressPrice: 610.00 },
    ],
    rating: 4.8,
    reviewCount: 68,
    imageIds: productImagesMap['sleigh-bed'].map(i => i.id),
    description: 'The Astral Sleigh Bed features a classic, gracefully curved headboard and footboard, upholstered in a sumptuous grey fabric. Its timeless silhouette brings an air of romance and sophistication to any bedroom.',
    details: ['Classic sleigh bed design with rolled headboard and footboard', 'Upholstered in premium, soft-touch fabric', 'Deep button tufting for a luxurious look', 'Solid wood feet for stability'],
    dimensions: { width: '145cm', height: '135cm', depth: '225cm' },
    style: 'Classic',
    material: 'Fabric',
    stock: 8,
  },
  {
    id: '13',
    slug: 'divan-ottoman-bed',
    name: 'Divan Ottoman Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 260.00,
    variants: [
      { size: 'Single', price: 260.00, mattressPrice: 580.00 },
      { size: 'Double', price: 320.00, mattressPrice: 400.00 },
      { size: 'King', price: 330.00, mattressPrice: 420.00 },
      { size: 'Super King', price: 370.00, mattressPrice: 460.00 },
    ],
    rating: 4.9,
    reviewCount: 78,
    imageIds: productImagesMap['divan-ottoman-bed'].map(i => i.id),
    description: 'A perfect blend of style and practicality, the Divan Ottoman Bed offers a huge amount of under-bed storage space without compromising on comfort. The gas-lift mechanism makes accessing your stored items effortless.',
    details: ['Powerful gas-lift ottoman mechanism', 'Large, fully-boarded storage area', 'Upholstered in high-quality linen fabric', 'Comes with a matching 24-inch headboard'],
    dimensions: { width: '142cm', height: '105cm', depth: '200cm' },
    style: 'Modern',
    material: 'Linen',
    stock: 20,
  },
  {
    id: '14',
    slug: 'florida-mirror-bed',
    name: 'Florida Mirror Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 300.00,
    variants: [
        { size: 'Single', price: 300.00, mattressPrice: 400.00 },
        { size: 'Double', price: 350.00, mattressPrice: 470.00 },
        { size: 'King', price: 400.00, mattressPrice: 540.00 },
        { size: 'Super King', price: 450.00, mattressPrice: 610.00 },
    ],
    rating: 4.9,
    reviewCount: 55,
    imageIds: productImagesMap['mirror-bed'].map(i => i.id),
    description: 'Reflect your sophisticated taste with the Florida Mirror Bed. Featuring striking mirrored panels on the headboard and footboard, this bed adds a touch of glamour and light to any bedroom, creating a sense of space and luxury.',
    details: ['Elegant mirrored panels on headboard and footboard', 'Upholstered in plush, silver velvet', 'Modern, clean-lined silhouette', 'Sturdy frame with sprung slats for comfort'],
    dimensions: { width: '142cm', height: '140cm', depth: '200cm' },
    style: 'Glamour',
    material: 'Velvet',
    stock: 9,
  },
  {
    id: '15',
    slug: 'panel-ambassador-bed',
    name: 'Panel Ambassador Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 280.00,
    variants: [
        { size: 'Single', price: 280.00, mattressPrice: 380.00 },
        { size: 'Double', price: 330.00, mattressPrice: 450.00 },
        { size: 'King', price: 380.00, mattressPrice: 520.00 },
        { size: 'Super King', price: 430.00, mattressPrice: 590.00 },
    ],
    rating: 4.8,
    reviewCount: 40,
    imageIds: productImagesMap['panel-ambassador-bed'].map(i => i.id),
    description: 'The Panel Ambassador Bed offers a contemporary take on a classic design. Its clean, vertical panels on the headboard create a sense of height and modernity, while the soft upholstery provides a comfortable and inviting feel.',
    details: ['Tall, vertically-paneled headboard', 'Upholstered in a sophisticated chenille fabric', 'Solid platform base for excellent support', 'Clean lines for a modern aesthetic'],
    dimensions: { width: '142cm', height: '150cm', depth: '200cm' },
    style: 'Contemporary',
    material: 'Chenille',
    stock: 15,
  },
  {
    id: '16',
    slug: 'panel-bumper-bed',
    name: 'Panel Bumper Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 270.00,
    variants: [
        { size: 'Single', price: 270.00, mattressPrice: 370.00 },
        { size: 'Double', price: 320.00, mattressPrice: 580.00 },
        { size: 'King', price: 370.00, mattressPrice: 510.00 },
        { size: 'Super King', price: 420.00, mattressPrice: 580.00 },
    ],
    rating: 4.9,
    reviewCount: 35,
    imageIds: productImagesMap['panel-bumper-bed'].map(i => i.id),
    description: 'With its fully upholstered frame and padded "bumper" sides, this bed offers a soft and safe sleeping environment. The clean lines of the paneled headboard provide a modern touch to this exceptionally comfortable bed.',
    details: ['Fully padded and upholstered bumper frame', 'Modern paneled headboard design', 'Soft-touch woven fabric', 'Excellent for homes with young children'],
    dimensions: { width: '142cm', height: '130cm', depth: '200cm' },
    style: 'Modern',
    material: 'Fabric',
    stock: 11,
  },
  {
    id: '17',
    slug: 'panel-line-bed',
    name: 'Panel Line Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 260.00,
    variants: [
        { size: 'Single', price: 260.00, mattressPrice: 360.00 },
        { size: 'Double', price: 320.00, mattressPrice: 440.00 },
        { size: 'King', price: 330.00, mattressPrice: 480.00 },
        { size: 'Super King', price: 370.00, mattressPrice: 530.00 },
    ],
    rating: 4.8,
    reviewCount: 38,
    imageIds: productImagesMap['panel-line-bed'].map(i => i.id),
    description: 'This bed features clean, modern lines with its distinctive vertically-paneled headboard. Upholstered in a durable and stylish fabric, it offers a sophisticated centerpiece for any contemporary bedroom.',
    details: ['Striking vertical panel stitching on headboard', 'Upholstered in premium textured fabric', 'Low-profile footboard for a modern look', 'Solid wood slat system for durable support'],
    dimensions: { width: '142cm', height: '135cm', depth: '200cm' },
    style: 'Contemporary',
    material: 'Fabric',
    stock: 14,
  },
  {
    id: '18',
    slug: 'panel-wing-back-bed',
    name: 'Panel Wing Back Bed',
    category: 'Beds',
    categorySlug: 'beds',
    price: 290.00,
    variants: [
        { size: 'Single', price: 290.00, mattressPrice: 390.00 },
        { size: 'Double', price: 340.00, mattressPrice: 460.00 },
        { size: 'King', price: 390.00, mattressPrice: 530.00 },
        { size: 'Super King', price: 440.00, mattressPrice: 600.00 },
    ],
    rating: 4.9,
    reviewCount: 42,
    imageIds: productImagesMap['panel-wing-back-bed'].map(i => i.id),
    description: 'A modern classic, the Panel Wing Back Bed features a grand, winged headboard with clean, vertical lines. It creates a cozy, enclosed feeling while making a bold style statement.',
    details: ['Grand wingback headboard design', 'Elegant vertical panel tufting', 'Upholstered in premium bouclé fabric', 'Provides a cozy, sheltered feel'],
    dimensions: { width: '145cm', height: '145cm', depth: '208cm' },
    style: 'Contemporary',
    material: 'Bouclé',
    stock: 10,
  },
];

export const reviews: Review[] = [
  { id: '1', productId: '1', author: 'Jane D.', rating: 5, title: 'Absolutely stunning!', comment: 'The sofa is even more beautiful in person. It\'s comfortable, stylish, and was delivered right on time. Highly recommend!', date: '2023-08-15' },
  { id: '2', productId: '1', author: 'Mark S.', rating: 4, title: 'Great sofa, minor issue', comment: 'Love the look and feel. One of the legs was slightly scratched on arrival, but customer service was fantastic and sent a replacement immediately.', date: '2023-08-20' },
  { id: '3', productId: '2', author: 'Emily R.', rating: 5, title: 'Perfect dining table', comment: 'This table is the heart of our home now. The quality of the oak is outstanding. We\'ve had so many compliments!', date: '2023-07-05' },
  { id: '4', productId: '3', author: 'Sarah K.', rating: 5, title: 'Bedroom transformed!', comment: 'The Cloud Nine bed is a dream. It was easy to assemble and has completely transformed our bedroom into a luxury retreat.', date: '2023-09-01' },
  { id: '5', productId: '4', author: 'Tom B.', rating: 4.5, title: 'Stylish and comfortable', comment: 'This armchair is the perfect reading chair. It\'s firm but comfortable and looks incredibly stylish in my living room.', date: '2023-09-10' },
  { id: '6', productId: '1', author: 'Chris P.', rating: 4, title: 'Solid and stylish', comment: 'A really great sofa for the price. It is firm, which I like. The color is slightly different than online but it still works.', date: '2023-09-15' },
  { id: '7', productId: '1', author: 'Jessica L.', rating: 5, title: 'My dream sofa!', comment: 'I am so in love with this sofa. It is the perfect size for my apartment and so comfortable. Assembly was surprisingly easy.', date: '2023-10-02' },
  { id: '8', productId: '2', author: 'David H.', rating: 5, title: 'Outstanding Quality', comment: 'Solid wood, beautifully finished. You can tell this table is built to last. Worth every penny.', date: '2023-09-22' },
  { id: '9', productId: '2', author: 'Laura C.', rating: 4, title: 'Beautiful but heavy!', comment: 'It\'s a gorgeous table, but be prepared, it is extremely heavy! You will need two people to assemble it.', date: '2023-10-11' },
  { id: '10', productId: '3', author: 'Michael B.', rating: 5, title: 'Sleeps like a baby', comment: 'I was hesitant to buy a bed online but this was a great decision. The headboard is so soft and it feels very sturdy.', date: '2023-09-05' },
  { id: '11', productId: '4', author: 'Olivia W.', rating: 5, title: 'The perfect accent chair', comment: 'This chair completed my living room. The leather is high quality and the wood has a beautiful grain. It\'s a work of art.', date: '2023-10-18' },
  { id: '12', productId: '5', author: 'Ben A.', rating: 5, title: 'Makes me want to work', comment: 'This desk is incredible. The walnut is beautiful and it has so much space. My home office finally feels complete.', date: '2023-09-28' },
  { id: '13', productId: '5', author: 'Chloe G.', rating: 4, title: 'Great desk, drawers a bit small', comment: 'I love the look and feel of the desk. The surface is huge. I just wish the drawers were a little deeper, but it\'s a minor complaint.', date: '2023-10-08' },
  { id: '14', productId: '6', author: 'Liam T.', rating: 5, title: 'Perfect for my apartment', comment: 'Fits perfectly in my small living room and holds a surprising number of books. It was also very easy to put together by myself.', date: '2023-10-14' },
  { id: '15', productId: '6', author: 'Sophia N.', rating: 3, title: 'Looks good, but feels a bit wobbly', comment: 'The shelf looks great, but it doesn\'t feel as sturdy as I\'d hoped. Definitely need to use the wall anchors it came with.', date: '2023-10-20' },
  { id: '16', productId: '7', author: 'Daniel R.', rating: 5, title: 'Elegant and functional', comment: 'This lamp is a showstopper. It provides great light for reading on the sofa and the marble base is very heavy and stable.', date: '2023-09-30' },
  { id: '17', productId: '7', author: 'Grace P.', rating: 4, title: 'Love it, but tricky to position', comment: 'A beautiful lamp. The arc is quite large, so make sure you have enough space for it. It took a few tries to get it in the perfect spot.', date: '2023-10-05' },
  { id: '18', productId: '8', author: 'Ethan K.', rating: 5, title: 'So soft and beautiful', comment: 'The rug feels amazing underfoot. The pattern is subtle but adds so much character to the room. It unrolled flat almost immediately.', date: '2023-09-18' },
  { id: '19', productId: '8', author: 'Mia V.', rating: 5, title: 'Completes the room!', comment: 'This rug was the final piece my living room needed. The quality is excellent and the colors are true to the photos online.', date: '2023-10-25' },
  { id: '20', productId: '4', author: 'Noah F.', rating: 5, title: 'My new favorite spot', comment: 'I find myself sitting in this chair all the time. It looks great and is surprisingly comfortable for long periods. A fantastic purchase.', date: '2023-10-28' },
  { id: '21', productId: '11', author: 'Olivia M.', rating: 5, title: 'Absolutely Regal!', comment: 'This bed is a statement piece. The headboard is massive and so luxurious. It feels like sleeping in a 5-star hotel every night. Worth every penny!', date: '2023-10-15' },
  { id: '22', productId: '11', author: 'Liam B.', rating: 5, title: 'Incredible build quality', comment: 'You can feel how sturdy this bed is. The crushed velvet is incredibly soft and the colour is beautiful. The delivery team was also very professional.', date: '2023-10-20' },
  { id: '23', productId: '11', author: 'Sophia T.', rating: 4, title: 'Stunning but HUGE!', comment: 'I am in love with this bed, it is absolutely stunning. Just a word of warning - make sure you measure your space! The headboard is very tall but it looks amazing.', date: '2023-10-28' },
  { id: '24', productId: '12', author: 'James P.', rating: 5, title: 'Classic and Comfortable', comment: 'This sleigh bed is perfect. It has a timeless look and it\'s incredibly comfortable. Assembly was straightforward and it feels very solid.', date: '2023-11-01' },
  { id: '25', productId: '12', author: 'Charlotte H.', rating: 4, title: 'Great value and looks expensive', comment: 'I\'m so pleased with this purchase. It looks much more expensive than it was. The fabric is soft and the button tufting is well done. A fantastic bed for the price.', date: '2023-10-25' },
  { id: '26', productId: '12', author: 'Amelia W.', rating: 5, title: 'Beautiful and elegant', comment: 'The bed is beautiful, and the curved headboard adds a really elegant touch to my bedroom. I opted for the mattress bundle and it\'s very comfortable.', date: '2023-11-05' },
  { id: '27', productId: '12', author: 'Noah F.', rating: 5, title: 'Fantastic Sleigh Bed', comment: 'I love the classic design of this bed. It was delivered quickly and was easy to assemble. The quality is great for the price.', date: '2023-11-08' },
  { id: '28', productId: '12', author: 'Emma G.', rating: 4.5, title: 'So cozy!', comment: 'This bed makes my room feel so cozy and romantic. The headboard is perfect for reading in bed. Highly recommended.', date: '2023-11-10' },
  { id: '29', productId: '12', author: 'Oliver T.', rating: 5, title: 'Great purchase!', comment: 'Really happy with this bed. It feels sturdy and looks fantastic. The delivery process was smooth and the communication was great.', date: '2023-11-12' },
  { id: '30', productId: '12', author: 'Isabella C.', rating: 5, title: 'A dream come true!', comment: 'I have always wanted a sleigh bed and this one is perfect. The quality is amazing and it looks so grand in my room. Five stars!', date: '2023-11-15' },
  { id: '31', productId: '12', author: 'George K.', rating: 4, title: 'Lovely bed', comment: 'A lovely bed, very well made. It was a bit tricky to get up the stairs as the headboard is large, so keep that in mind. But once assembled, it\'s fantastic.', date: '2023-11-18' },
  { id: '32', productId: '12', author: 'Hannah L.', rating: 5, title: 'So luxurious', comment: 'The fabric is so soft and the bed feels incredibly luxurious. I\'m so happy with my purchase. It has completely changed the feel of my bedroom.', date: '2023-11-20' },
  { id: '33', productId: '12', author: 'Ava J.', rating: 5, title: 'Simply Stunning', comment: 'I am so impressed with this bed. The quality is exceptional and it looks so grand in our master bedroom. It has exceeded all my expectations. The delivery was also quick and the setup was easy. Highly recommend it to anyone looking for a statement piece.', date: '2023-11-21' },
  { id: '34', productId: '12', author: 'William D.', rating: 4, title: 'Great Bed, Great Price', comment: 'For the price, you cannot beat the quality of this bed. It feels very solid and the upholstery is well done. It was a bit of a challenge to assemble on my own, but I managed it. Overall, a fantastic buy.', date: '2023-11-22' },
  { id: '35', productId: '12', author: 'Mia L.', rating: 5, title: 'Elegant and Timeless', comment: 'This sleigh bed is a timeless piece. It brings a touch of elegance to my bedroom without being overly ornate. The fabric is a beautiful neutral grey that goes with everything. I\'m thrilled with this purchase.', date: '2023-11-24' },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: '10-tips-for-choosing-the-perfect-sofa',
    title: '10 Tips for Choosing the Perfect Sofa',
    author: 'The Furnishr Team',
    date: 'October 26, 2023',
    imageId: 'blog-1',
    excerpt: 'Your sofa is the centerpiece of your living room. Here are 10 essential tips to help you choose a sofa that you\'ll love for years to come...',
    content: '<h2>Introduction</h2><p>Choosing a sofa is a big decision. It\'s often one of the largest and most-used pieces of furniture in a home. In this guide, we\'ll walk you through 10 key considerations...</p><h3>1. Measure Your Space</h3><p>Before you even start looking, measure the room, doorways, and stairwells to ensure your new sofa will fit. Don\'t forget to account for diagonal measurements of doorways! Use masking tape on the floor to outline the sofa\'s dimensions to get a real feel for how it will occupy the space.</p><h3>2. Consider Your Lifestyle</h3><p>Do you have children or pets? If so, opt for durable, stain-resistant fabrics like performance velvet or a tight-weave linen blend. If it\'s just for you, you might indulge in a more delicate material.</p><h3>3. Define Your Style</h3><p>Are you a mid-century modern enthusiast or do you prefer a classic, traditional look? Your sofa choice should complement your home\'s existing decor. Look at the legs, arm style, and overall silhouette.</p>',
    imageUrl: blogImagesMap['blog-1'].imageUrl,
    imageHint: blogImagesMap['blog-1'].imageHint
  },
  {
    id: '2',
    slug: 'how-to-style-a-small-living-space',
    title: 'How to Style a Small Living Space for Maximum Impact',
    author: 'The Furnishr Team',
    date: 'November 05, 2023',
    imageId: 'blog-2',
    excerpt: 'Living in a small space doesn\'t mean you have to compromise on style. With a few clever tricks, you can make your compact home feel spacious and chic...',
    content: '<h2>Embrace Multifunctionality</h2><p>In a small space, every piece of furniture should work hard. Think coffee tables with hidden storage, ottomans that double as seating, or sofas that convert into beds. This reduces clutter and maximizes utility.</p><h3>2. Go Vertical</h3><p>Utilize wall space with tall, narrow bookshelves and floating shelves to draw the eye upward and free up floor space. This creates an illusion of height and provides valuable storage and display areas without bulk.</p><h3>3. Use Light and Mirrors</h3><p>Mirrors are a small space\'s best friend. They reflect light and create a sense of depth, making the room feel larger. Position a large mirror opposite a window to maximize natural light. Choose a light color palette for walls and large furniture pieces to keep the space feeling airy and open.</p>',
    imageUrl: blogImagesMap['blog-2'].imageUrl,
    imageHint: blogImagesMap['blog-2'].imageHint
  },
  {
    id: '3',
    slug: 'biophilic-design-bringing-the-outdoors-in',
    title: 'Biophilic Design: Bringing the Outdoors In',
    author: 'The Furnishr Team',
    date: 'November 12, 2023',
    imageId: 'blog-3',
    excerpt: 'Discover how to incorporate natural elements into your home to create a calming, healthier, and more beautiful living environment. It\'s easier than you think...',
    content: '<h2>What is Biophilic Design?</h2><p>Biophilic design is an architectural and interior design approach that seeks to connect building occupants more closely to nature. Incorporating natural lighting, ventilation, plant life, and natural materials like wood and stone can reduce stress and improve well-being.</p><h3>1. Start with Plants</h3><p>The easiest way to begin is by adding houseplants. They purify the air and add a splash of color and life. Choose a variety of sizes and types, from large floor plants like a Fiddle Leaf Fig to small succulents on a windowsill.</p><h3>2. Natural Materials</h3><p>Incorporate materials that come from the earth. Think wooden furniture, stone countertops, linen curtains, and wool rugs. These textures add warmth and a sense of grounding to your space. Our Nordic Oak Dining Table is a perfect example!</p>',
    imageUrl: blogImagesMap['blog-3'].imageUrl,
    imageHint: blogImagesMap['blog-3'].imageHint
  }
];

export const faqs: Faq[] = [
    {
      id: '1',
      question: 'What payment methods do you accept?',
      answer: 'We accept all major credit cards (Visa, Mastercard, American Express), as well as PayPal, Klarna, Apple Pay, and Google Pay for a secure and seamless checkout experience.',
      category: 'Ordering',
    },
    {
      id: '2',
      question: 'How can I track my order?',
      answer: 'Once your order has shipped, you will receive an email with a tracking number and a link to the courier\'s website. You can use this to monitor your delivery status.',
      category: 'Shipping & Delivery',
    },
    {
      id: '3',
      question: 'What is your return policy?',
      answer: 'We offer a 30-day hassle-free return policy. If you are not completely satisfied with your purchase, you can return it within 30 days for a full refund or exchange. Please ensure the item is in its original condition and packaging.',
      category: 'Returns & Exchanges',
    },
    {
      id: '4',
      question: 'Do you offer free shipping?',
      answer: 'Yes, we offer free standard UK delivery on all orders over £250. For orders under £250, a standard delivery fee applies.',
      category: 'Shipping & Delivery',
    },
    {
      id: '5',
      question: 'Do your products come with a warranty?',
      answer: 'Absolutely. All our furniture comes with a 1-year manufacturer\'s warranty covering any defects in materials or craftsmanship. We stand by the quality of our products.',
      category: 'Product Information',
    },
    {
      id: '6',
      question: 'Can I cancel or change my order?',
      answer: 'You can cancel or modify your order within 24 hours of placing it. Please contact our customer service team as soon as possible. After 24 hours, the order may have already been processed for shipping.',
      category: 'Ordering',
    },
     {
      id: '7',
      question: 'How do I care for my new furniture?',
      answer: 'Each product comes with specific care instructions. Generally, we recommend dusting regularly, avoiding direct sunlight, and cleaning spills immediately with a dry cloth. For specific materials like leather or velvet, please refer to the care guide included with your item.',
      category: 'Product Information',
    },
];

export const featuredProducts: Product[] = [];

export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);
export const getBlogBySlug = (slug: string) => blogPosts.find(p => p.slug === slug);

    










    

    














    


    











